from sqlalchemy import Column, Float, Integer, String
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()


class CsvData(Base):
    __tablename__ = "csv_data"

    id = Column(Integer, primary_key=True, autoincrement=True)
    net_sales_taxfree = Column(Float, name="net_sales_taxfree")
    net_sales_vat_20 = Column(Float, name="net_sales_vat_20")
    net_sales_vat_10 = Column(Float, name="net_sales_vat_10")
    total_net_sales_1 = Column(Float, name="total_net_sales_1")
    net_sales_other = Column(Float, name="net_sales_other")
    total_revenue = Column(Float, name="total_revenue")
    food = Column(Float, name="food")
    beverages = Column(Float, name="beverages")
    employee_meals = Column(Float, name="employee_meals")
    packing = Column(Float, name="packing")
    freight = Column(Float, name="freight")
    cost_of_goods = Column(Float, name="cost_of_goods")
    wages_employees = Column(Float, name="wages_employees")
    salaries_management = Column(Float, name="salaries_management")
    payroll_taxes = Column(Float, name="payroll_taxes")
    bonus_management = Column(Float, name="bonus_management")
    total_personnel_costs = Column(Float, name="total_personnel_costs")
    car = Column(Float, name="car")
    travel_expenses = Column(Float, name="travel_expenses")
    advertising_banners_spots = Column(Float, name="advertising_banners_spots___")
    advertising_influencers = Column(Float, name="advertising_influencers")
    decoration = Column(Float, name="decoration")
    waste_disposal = Column(Float, name="waste_disposal")
    external_service = Column(Float, name="external_service")
    delivery_cost = Column(Float, name="delivery_cost")
    rep__mantenance_costs = Column(Float, name="rep___mantenance_costs")
    ops_operating_materials = Column(Float, name="ops_operating_materials")
    cleaning_material = Column(Float, name="cleaning_material")
    office_expenses = Column(Float, name="office_expenses")
    workwear = Column(Float, name="workwear")
    energy_costs = Column(Float, name="energy_costs")
    other_costs = Column(Float, name="other_costs")
    total_controllable_costs = Column(Float, name="total_controllable_costs")
    costs = Column(Float, name="costs")
    operating_income_gp = Column(Float, name="operating_income_gp")
    rent = Column(Float, name="rent")
    other_operating_costs = Column(Float, name="other_operating_costs")
    staff_apartment = Column(Float, name="staff_apartment")
    administration = Column(Float, name="administration")
    md_costs = Column(Float, name="md_costs")
    fin_and_legal_advice = Column(Float, name="fin__and_legal_advice")
    insurance = Column(Float, name="insurance")
    money_transfer = Column(Float, name="money_transfer")
    interest = Column(Float, name="interest")
    interests = Column(Float, name="interests")
    franchise_fee = Column(Float, name="franchise_fee")
    leasing = Column(Float, name="leasing")
    depreciation = Column(Float, name="depreciation")
    total_non_contr_costs = Column(Float, name="total_non_contr__costs")
    other_expenses = Column(Float, name="other_expenses")
    other_income = Column(Float, name="other_income")
    ebitda = Column(Float, name="ebitda")
    depreciation_2 = Column(Float, name="depreciation_2")
    leasing_2 = Column(Float, name="leasing_2")
    ebitdal = Column(Float, name="ebitdal")
    tax_assumption = Column(Float, name="tax_assumption")
    net = Column(Float, name="net")
